### ISSUE TITLE
Setting phase status

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/hub-gradle-plugin#21]
In the hub teamcity plugin it's possible to set the phase status to "In Development" or "Released". I don't see an option for that here. Are there plans to add that option?

**Comment by jrichardBD** [comment]
That option in TeamCity will be removed soon.  Controlling the phase and distribution will be managed in the Hub

**Comment by imbeyondboredom** [comment]
Thanks for the clarity!
