### ISSUE TITLE
File path is relative instead of complete

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/hub-gradle-plugin#23]
Using the hub plugin we get complete file paths for the code:
file://[hostname]/home/[user]/[folder]/work/[repo]/

But using the gradle plugin we only get a relative path:
mvn:/[folder]/[version]

We have some projects that have a standard of putting their code in a "Code" folder so this makes all of them look the same.

/
  Documentation/
  Code/
       build.gradle

Results in:
mvn:/Code/3.2.1

**Comment by ekerwin** [comment]
What issue does having different paths create? Can you provide the bdio file you are getting? Do the different paths affect the final bom in a way you wouldn't expect or is this just a concern over cosmetics?

**Comment by imbeyondboredom** [comment]
The issue is different projects are overwriting the same BOMs in the blackduck hub because the "Code Location" is partial.

So if I have 
Project A/
Project A/Code/
Project A/Code/build.gradle

and 

Project B/
Project B/Code/
Project B/Code/build.gradle

And they share the same version numbers then they override each other when scanned:
mvn:/Code/3.2.1

Ideally the Code location in blackduck hub would follow the same scheme as the scans that the hub tool uses:
file://[hostname]/[complete_path]
Example:
file://mymac/Users/myuser/Documents/repos/MyRepo/npm-shrinkwrap.json#declared-components

**Comment by ekerwin** [comment]
The code location is constructed from your project's gav. With the 3.4.1 version of the plugin, against my own gradle project, it produces a code location of the form:

mvn:GROUP/ARTIFACT/VERSION

It seems like we are not correctly handling your gradle usage. Is your usage documented somewhere so we can investigate how it differs from what we expect?

I specify group and version in my build.gradle and my artifact is specified in settings.gradle.

Here are some more details on why we support that method, but if you have another way of using gradle, maybe we can support that as well.

http://stackoverflow.com/questions/24827733/how-do-you-set-the-maven-artifact-id-of-a-gradle-project

**Comment by imbeyondboredom** [comment]
Ah so my use case is based on Android apps. Basically none of them have the group or artifact specified because they're never going to be used in another project. So as a result every app we have defaults to the parent directory which in our case is "Code".

I think that what you've stated is a good default although it does break from the scheme which the other scanning tools (TeamCity plugin, Black Duck CLI tool) use. Would it be possible to add a configuration flag to change the behavior to match the other scanning tools?

**Comment by imbeyondboredom** [comment]
Following your link I realized we can get close to this behavior by using the following config:

apply plugin: "java"
group = projectDir

I think this will work for me although it is a bit hacky. I'll leave it up to you all if you want to leave this open or close it

**Comment by ekerwin** [comment]
I'd like to leave this open to track the new feature to allow for a path override. Your use case, at least to me, sounds completely reasonable and we should attempt to support it. I'll close this when we release with a fix.

**Comment by psantos1113** [comment]
I believe the source of the problem is in the content of the Project node in the BDIO files.  Can we get the BDIO files by chance to investigate further?  If we cannot get the full file contents could you find the project node and include that?  We would like examples of the BDIO files for project A and B for comparison if possible.

An example of the project node data:

 {
  "@id" : "mvn:/Code/1.2.0-SNAPSHOT",
  "@type" : "Project",
  "name" : "Code/ProjectA",
  "revision" : "1.2.0-SNAPSHOT",
  "externalIdentifier" : {
    "externalSystemTypeId" : "maven",
    "externalId" : ":Code:1.2.0-SNAPSHOT"
  },

We're interested in at least that data shown above just to see if we can confirm with our internal tests.

**Comment by imbeyondboredom** [comment]
@psantos1113 This problem was already solved in that the reason that this doesn't work for the android projects I have is because by default the group becomes the containing folder. I solved this by setting the group to be the project directory on my end but I could just have easily enforced that every one of my projects set the group themselves. I just chose to use the full path to make it match hub scans and because I dynamically inject the plugin into our projects using something similar to [this](https://gist.github.com/imbeyondboredom/807e0367e019a152e143cae69b4b52a3). This problem is unrelated to #26 which solves #25 IMO

Here's the information you asked for though: (Note this is if I turn off my hack that makes my ids different):
{
  "@id" : "mvn:/Code/1.2",
  "@type" : "Project A",
  "name" : "Project A",
  "revision" : "1.2",
  "externalIdentifier" : {
    "externalSystemTypeId" : "maven",
    "externalId" : ":Code:1.2"
  },

and 
{
  "@id" : "mvn:/Code/4.2",
  "@type" : "Project",
  "name" : "Project B",
  "revision" : "4.2",
  "externalIdentifier" : {
    "externalSystemTypeId" : "maven",
    "externalId" : ":Code:4.2"
  },

**Comment by psantos1113** [comment]
Based on the research I've done I have two questions.  
1. Are ProjectA and ProjectB described in issue modules of the same android application?  
2. Or are they separate applications but each build.gradle file defines the applicationId property?

As described [here](https://developer.android.com/studio/build/index.html) for android development.  If you have an artifactId property set in the build.gradle then we should look for that perhaps and use it.  If they are modules of the same application we would also want support for sub projects which is a feature coming in the future.

**Comment by imbeyondboredom** [comment]
@psantos1113 It's number 2. They're both completely separate apps. It would be great if it could use the applicationId with the version name and version code (Although version code for us changes every build so including that I would want to be optional)

Worst case Android apps can solve this by just properly defining the group and artifact ID but this would be a nice to have.

**Comment by akamen** [comment]
@imbeyondboredom  After trying it with the just released 4.0.0 - can you let us know if this is still an issue?

**Comment by imbeyondboredom** [comment]
This seems to use the ProjectName and Version instead of the file path correctly now with the addition of the code location so this all should work as intended! Closing
